"""Shared configuration for gbrain services."""
import math
import os
from dataclasses import dataclass, field

from services.shared.tool_gating import parse_tool_set


def _require_pg_password() -> str:
    """Read PG_PASSWORD from env, fail loudly with a clear remediation hint.

    install.sh generates this at install time and writes it to both the .env
    and the systemd EnvironmentFile (/etc/gbrain/secrets.env). If you see this
    error, the most likely cause is that you bypassed install.sh or that the
    secrets file is missing — re-run install.sh, or inspect
    /etc/gbrain/secrets.env to confirm PG_PASSWORD is present.
    """
    pw = os.environ.get("PG_PASSWORD")
    if pw is None:
        raise RuntimeError(
            "PG_PASSWORD is not set. It is generated by scripts/install.sh and "
            "written to /etc/gbrain/secrets.env. Re-run install.sh or export "
            "PG_PASSWORD manually before starting services."
        )
    return pw


def _env_float(name: str, default: str, min_value: float = 0.0) -> float:
    """Parse a float env var with a default and a lower bound.

    Args:
        name: Environment variable name.
        default: Default string value used when the env var is unset.
        min_value: Minimum allowed numeric value (inclusive).

    Returns:
        Parsed float.

    Raises:
        RuntimeError: If the value is not a float or is below ``min_value``.
    """
    raw = os.environ.get(name, default)
    try:
        value = float(raw)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(
            f"{name} must be a float, got: {raw!r}"
        ) from exc
    if not math.isfinite(value):
        raise RuntimeError(
            f"{name} must be finite, got {raw!r}"
        )
    if value < min_value:
        raise RuntimeError(
            f"{name} must be >= {min_value}, got: {value}"
        )
    return value


def _env_int(
    name: str,
    default: str,
    min_value: int = 0,
    max_value: int | None = None,
) -> int:
    """Parse an int env var with a default and inclusive bounds.

    Args:
        name: Environment variable name.
        default: Default string value used when the env var is unset.
        min_value: Minimum allowed integer (inclusive).
        max_value: Optional maximum allowed integer (inclusive).

    Returns:
        Parsed int.

    Raises:
        RuntimeError: If the value is not an int or is out of range.
    """
    raw = os.environ.get(name, default)
    try:
        value = int(raw)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(
            f"{name} must be an int, got: {raw!r}"
        ) from exc
    if value < min_value:
        raise RuntimeError(
            f"{name} must be >= {min_value}, got: {value}"
        )
    if max_value is not None and value > max_value:
        raise RuntimeError(
            f"{name} must be <= {max_value}, got: {value}"
        )
    return value


@dataclass(frozen=True)
class Config:
    """Service configuration loaded from environment variables."""

    pg_host: str = field(
        default_factory=lambda: os.environ.get("PG_HOST", "/var/run/postgresql")
    )
    pg_port: int = field(
        default_factory=lambda: int(os.environ.get("PG_PORT", "5432"))
    )
    pg_database: str = field(
        default_factory=lambda: os.environ.get("PG_DATABASE", "gbrain")
    )
    pg_user: str = field(
        default_factory=lambda: os.environ.get("PG_USER", "gbrain")
    )
    pg_password: str = field(
        default_factory=_require_pg_password
    )
    vault_root: str = field(
        default_factory=lambda: os.environ.get(
            "VAULT_ROOT", "/opt/gbrain/vault"
        )
    )
    fastembed_model: str = field(
        default_factory=lambda: os.environ.get(
            "FASTEMBED_MODEL", "intfloat/multilingual-e5-large"
        )
    )
    mcp_host: str = field(
        default_factory=lambda: os.environ.get("MCP_HOST", "0.0.0.0")
    )
    mcp_port: int = field(
        default_factory=lambda: int(os.environ["MCP_PORT"])
    )
    gbrain_tools: str = field(
        default_factory=lambda: parse_tool_set(os.environ.get("GBRAIN_TOOLS"))
    )
    rrf_weight_bm25: float = field(
        default_factory=lambda: _env_float("GBRAIN_RRF_WEIGHT_BM25", "0.4")
    )
    rrf_weight_vec: float = field(
        default_factory=lambda: _env_float("GBRAIN_RRF_WEIGHT_VEC", "0.6")
    )
    diversify_max: int = field(
        default_factory=lambda: _env_int(
            "GBRAIN_DIVERSIFY_MAX", "0", min_value=0, max_value=100
        )
    )

    def get_pg_dsn(self) -> dict[str, str | int]:
        """Return asyncpg connection kwargs.

        Uses unix socket when pg_host starts with '/', TCP otherwise.
        """
        base: dict[str, str | int] = {
            "database": self.pg_database,
            "user": self.pg_user,
            "password": self.pg_password,
            "host": self.pg_host,
        }
        # Only include explicit port for TCP. Unix-socket hosts (paths starting
        # with '/') ignore port but asyncpg is happy either way.
        if not self.pg_host.startswith("/"):
            base["port"] = self.pg_port
        return base
